export enum ActionType {
  FETCH_COLLECTIONS_INFO = "FETCH_COLLECTIONS_INFO",
  RECEIVE_COLLECTIONS_INFO = "RECEIVE_COLLECTIONS_INFO",
  SOME_ERROR = "SOME_ERROR",
  FETCH_COLLECTION_ASSETS = "FETCH_COLLECTION_ASSETS",
  RECEIVE_COLLECTION_ASSETS = "RECEIVE_COLLECTION_ASSETS",
}
