export enum ActionType {
  FETCH_COLLECTIONS_INFO = 'FETCH_COLLECTIONS_INFO',
  RECEIVE_COLLECTIONS_INFO = 'RECEIVE_COLLECTIONS_INFO',
  ASSETS_UPDATED = 'ASSETS_UPDATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  COLLECTIONS_UPDATED = 'COLLECTIONS_UPDATED',
  COLLECTION_UPDATED = 'COLLECTIONS_UPDATED',
  DISCONNECT = 'DISCONNECT',
  CONNECT = 'CONNECT',
}
